#!/bin/bash
# 统一按钮状态管理 - 测试启动脚本

echo "========================================"
echo "统一按钮状态管理 - Phase 1-3 测试"
echo "========================================"
echo ""
echo "已完成:"
echo "✅ Phase 1: 按钮样式统一"
echo "✅ Phase 2: 状态管理重构 (dcc.Store + Clientside Callback)"
echo "✅ Phase 3: 语音组件集成"
echo ""
echo "待测试:"
echo "📋 场景1: 文本聊天流程"
echo "📋 场景2: 语音录音流程"
echo "📋 TTS配置控制"
echo "📋 边界情况处理"
echo ""
echo "----------------------------------------"
echo "启动应用进行测试..."
echo "----------------------------------------"
echo ""
echo "1. 确保后端服务已启动"
echo "2. 打开浏览器访问: http://localhost:8050"
echo "3. 打开开发者工具 (F12) 查看Console日志"
echo "4. 测试以下场景:"
echo ""
echo "   场景1: 文本聊天"
echo "   - 输入文本，点击发送"
echo "   - 观察按钮状态变化: text_processing → preparing_tts → playing_tts → idle"
echo "   - 检查Console日志中的状态更新"
echo ""
echo "   场景2: 语音录音"
echo "   - 点击录音按钮"
echo "   - 说话后点击停止"
echo "   - 观察状态变化: recording → voice_processing → text_processing → preparing_tts → playing_tts → idle"
echo ""
echo "   场景3: 空输入测试"
echo "   - 不输入任何内容，点击发送"
echo "   - 应该显示警告: \"请输入消息内容\""
echo ""
echo "预期Console日志格式:"
echo "  - State update: {state: 'xxx', timestamp: xxx, metadata: {...}}"
echo "  - UI update for state: xxx"
echo "  - 录音开始，触发状态更新"
echo "  - TTS播放开始，触发状态更新"
echo ""
echo "----------------------------------------"
echo "按Ctrl+C退出测试"
echo "----------------------------------------"
echo ""

# 启动应用
python app.py

